rmdir /s /q "Orcbolg.Dsp\bin"
rmdir /s /q "Orcbolg.Dsp\obj"
rmdir /s /q "Orcbolg.Dsp.Test\bin"
rmdir /s /q "Orcbolg.Dsp.Test\obj"
rmdir /s /q "Orcbolg.Recog\bin"
rmdir /s /q "Orcbolg.Recog\obj"
rmdir /s /q "Orcbolg.Recog.Test\bin"
rmdir /s /q "Orcbolg.Recog.Test\obj"
rmdir /s /q "Rockon\bin"
rmdir /s /q "Rockon\obj"
rmdir /s /q "Workspace\bin"
rmdir /s /q "Workspace\obj"
pause
